services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      # Hindari me-mount node_modules dari host jika ada perbedaan OS
      - /app/node_modules
    networks:
      - shared-network

networks:
  shared-network:
    external: true
