/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "error": "#ffb4ab",
        "on-tertiary": "#442b14",
        "inverse-on-surface": "#303032",
        "secondary-fixed": "#ffdf9e",
        "tertiary-container": "#210d00",
        "surface-container-lowest": "#0e0e10",
        "on-tertiary-fixed": "#2c1603",
        "surface": "#131315",
        "surface-dim": "#131315",
        "on-surface": "#e5e2e4",
        "primary-fixed": "#dce1ff",
        "tertiary-fixed-dim": "#e8be9f",
        "surface-container": "#1f1f21",
        "outline": "#909098",
        "on-primary": "#292f48",
        "on-tertiary-container": "#9a765b",
        "tertiary": "#e8be9f",
        "on-primary-container": "#767c99",
        "background": "#131315",
        "surface-container-high": "#2a2a2c",
        "on-tertiary-fixed-variant": "#5e4029",
        "inverse-surface": "#e5e2e4",
        "outline-variant": "#46464d",
        "primary": "#bfc5e4",
        "on-primary-fixed": "#141a32",
        "on-secondary-container": "#6a4e00",
        "primary-fixed-dim": "#bfc5e4",
        "on-secondary-fixed-variant": "#5b4300",
        "error-container": "#93000a",
        "on-background": "#e5e2e4",
        "surface-container-highest": "#353436",
        "on-error": "#690005",
        "inverse-primary": "#575d78",
        "surface-tint": "#bfc5e4",
        "secondary-fixed-dim": "#fabd00",
        "on-surface-variant": "#c6c6ce",
        "tertiary-fixed": "#ffdcc3",
        "on-error-container": "#ffdad6",
        "secondary-container": "#fabd00",
        "on-secondary-fixed": "#261a00",
        "surface-variant": "#353436",
        "on-secondary": "#3f2e00",
        "primary-container": "#0a1128",
        "on-primary-fixed-variant": "#3f465f",
        "secondary": "#ffdf9e",
        "surface-bright": "#39393b",
        "surface-container-low": "#1b1b1d"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "xl": "80px",
        "gutter": "24px",
        "lg": "48px",
        "sm": "12px",
        "container-max": "1440px",
        "base": "8px",
        "md": "24px",
        "xs": "4px"
      },
      "fontFamily": {
        "display-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "title-md": ["Inter"],
        "label-caps": ["Inter"],
        "data-mono": ["Inter"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"]
      },
      "fontSize": {
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "title-md": ["20px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "data-mono": ["18px", { "lineHeight": "1", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
